version: '3.3'

services:
  ddclient-noip:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient-noip
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config/ddclient.conf.noip:/config/ddclient.conf
    networks:
      docker:
    logging:
      options:
        max-size: 100M

  ddclient-dedyn:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient-dedyn
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config/ddclient.conf.dedyn:/config/ddclient.conf
    networks:
      docker:
    logging:
      options:
        max-size: 100M

networks:
  docker:
